version: '3.4'

services:

  selenium.chrome:
    image: selenium/standalone-chrome:3.141.59
    container_name: selenium.chrome
    ports:
      - 4444:4444

  scrapy:
    image: ${DOCKER_REGISTRY-}scrapy
    build:
      context: .
      dockerfile: scrapy/Dockerfile
    depends_on:
      - selenium.chrome

