version: '3.4'

services:

  selenium.chrome:
    image: selenium/standalone-chrome:3.141.59
    container_name: selenium.chrome
    ports:
      - 4444:4444

  fishslice:
    image: ${DOCKER_REGISTRY-}fishslice
    build:
      context: .
      dockerfile: fishslice/Dockerfile
    depends_on:
      - selenium.chrome

